"preserve-hierarchy": true
"files": [
  {
    "source": "/crowdin/Guides/**/*",
    "translation": "/i18n/%two_letters_code%/%original_file_name%",
    "update_option": "update_as_unapproved",
    "dest": "Guides/**/%original_file_name%",
  }
]
