name: Push preview to master and deploy to live
on: workflow_dispatch

jobs:
  deploy-preview:
    name: Push preview to master and deploy to live
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: preview
          fetch-depth: 0


      - name: Build the site
        run: ./build.sh

      - name: Push preview to master
        run: git push origin preview:master

      - name: Deploy to Netlify
        run: ./deploy.sh --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
